# _config.yml para GitHub Pages / Jekyll

# Carpeta de origen de tu web (donde est치 tu index.html / assets)
source: apps/web

# Carpeta de destino donde se genera el sitio est치tico
destination: _site

# Ignorar archivos y carpetas innecesarias
exclude:
  - node_modules
  - apps/api/node_modules
  - apps/web/node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - CHANGELOG.md

# Configuraci칩n de tema (opcional)
theme: jekyll-theme-primer

# Configuraci칩n de plugins (solo si los usas)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Evitar procesar archivos ocultos
keep_files:
  - ".gitignore"
